name: grouped_infinite_list
description: Grouped Infinite ListView with items that can be scrolled infinitely in both directions.
version: 0.2.0
repository: https://github.com/jarjut/grouped_infinite_list

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ">=0.3.0 <2.0.0"
  very_good_analysis: ^3.1.0
